server:
  port: 8081

spring:
  application:
    name: training-aggregator

  datasource:
    url: jdbc:h2:mem:workload_db
    username: db_user
    password: db_password
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

  activemq:
    broker-url: "tcp://localhost:61616?jms.redeliveryPolicy.maximumRedeliveries=3"
    user: admin
    password: admin

messaging:
  trainer-workload-queue: trainer.workload.queue

logging:
  level:
    root: INFO

  pattern:
    console: "%X{transactionId} %msg%n"

security:
  jwt:
    publicKey: classpath:keys/public.pem
    issuer: gym-system